package dev.warsha.remoteble.tools.core

import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

expect fun environmentVariable(name: String): String?
expect fun homeDirectory(): String
expect fun isApplePlatform(): Boolean
expect fun fileExists(path: String): Boolean
expect fun readFileText(path: String): String
/** Reads bounded lines incrementally without materializing the complete file. */
expect fun forEachFileLine(path: String, maximumLineBytes: Int, consume: (String) -> Unit)
expect fun readStandardInput(maximumBytes: Int): ByteArray
/** Reads one line without tying session shutdown to an indefinitely blocked terminal or pipe. */
expect suspend fun readStandardInputLine(maximumBytes: Int = 64 * 1024): String?
/** Installs a scoped foreground Ctrl-C handler, returning false when the runtime cannot provide one. */
expect fun installInterruptHandler(): Boolean
/** Restores the handler that was active before [installInterruptHandler]. */
expect fun restoreInterruptHandler()
/** Returns and clears one foreground Ctrl-C request while the scoped handler is installed. */
expect fun consumeInterrupt(): Boolean
expect fun writeStandardOutput(bytes: ByteArray)
expect fun writeStandardError(bytes: ByteArray)
expect fun appendFileText(path: String, value: String)
expect fun writeFileText(path: String, value: String)
/** Replaces [path] only after a complete owner-only temporary file has been flushed. */
expect fun writeFileTextAtomically(path: String, value: String)
/** Writes only when [path] does not yet exist; returns false when another process won the race. */
expect fun writeFileTextIfAbsent(path: String, value: String): Boolean
expect fun ensureDirectory(path: String)
expect fun listDirectory(path: String): List<String>
expect fun deleteFile(path: String)
expect fun setOwnerOnly(path: String, directory: Boolean)
expect fun <T> withFileLock(path: String, block: () -> T): T

@OptIn(ExperimentalUuidApi::class)
fun defaultClientIdentity(): String = "rble-auto-" + Uuid.random().toString().replace("-", "")

/** Loads one machine identity for reconnects, creating it once with owner-only permissions. */
fun persistedClientIdentity(): String {
    val path = environmentVariable("REMOTE_BLE_CLIENT_ID_FILE")
        ?: (homeDirectory().trimEnd('/') + "/.config/remoteble/client-id")
    try {
        ensureDirectory(path.substringBeforeLast('/'))
        return withFileLock("$path.lock") {
            if (fileExists(path)) return@withFileLock validateClientIdentity(readFileText(path).trim())
            val identity = defaultClientIdentity()
            if (writeFileTextIfAbsent(path, identity + "\n")) {
                setOwnerOnly(path, directory = false)
                identity
            } else {
                validateClientIdentity(readFileText(path).trim())
            }
        }
    } catch (error: CliFailure) {
        throw error
    } catch (error: Throwable) {
        throw CliFailure(ExitCode.FAILURE, "unable to load the persisted client identity", error)
    }
}

fun isAutoGeneratedClientIdentity(value: String): Boolean =
    Regex("^rble-auto-[0-9a-f]{32}$").matches(value)

fun validateClientIdentity(value: String): String {
    if (!Regex("^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$").matches(value)) {
        throw CliFailure(ExitCode.USAGE, "client id must be 8-128 characters using letters, digits, '.', '_', ':' or '-'")
    }
    return value
}
