package dev.warsha.remoteble.tools.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.CliktError
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.core.PrintHelpMessage
import com.github.ajalt.clikt.core.ProgramResult
import com.github.ajalt.clikt.completion.completionOption
import com.github.ajalt.clikt.core.UsageError
import com.github.ajalt.clikt.core.parse
import com.github.ajalt.clikt.core.subcommands
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.arguments.optional
import com.github.ajalt.clikt.parameters.groups.OptionGroup
import com.github.ajalt.clikt.parameters.groups.provideDelegate
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.multiple
import com.github.ajalt.clikt.parameters.options.required
import com.github.ajalt.clikt.parameters.options.versionOption
import com.github.ajalt.clikt.parameters.types.choice
import com.github.ajalt.clikt.parameters.types.int
import dev.warsha.remoteble.protocol.AdvertisementDto
import dev.warsha.remoteble.protocol.Capabilities
import dev.warsha.remoteble.protocol.ScanFilter
import dev.warsha.remoteble.protocol.AgentStatusDto
import dev.warsha.remoteble.tools.core.AgentFeature
import dev.warsha.remoteble.tools.core.AuditLogger
import dev.warsha.remoteble.tools.core.WriteOperationService
import dev.warsha.remoteble.tools.core.RemoteOperationService
import dev.warsha.remoteble.tools.core.CliFailure
import dev.warsha.remoteble.tools.core.ConfigLoader
import dev.warsha.remoteble.tools.core.DeviceSelection
import dev.warsha.remoteble.tools.core.ExitCode
import dev.warsha.remoteble.tools.core.FileConfig
import dev.warsha.remoteble.tools.core.RemoteBleGateway
import dev.warsha.remoteble.tools.core.ResolvedConfig
import dev.warsha.remoteble.tools.core.collectBoundedStream
import dev.warsha.remoteble.tools.core.base64
import dev.warsha.remoteble.tools.core.escapeDeviceText
import dev.warsha.remoteble.tools.core.environmentVariable
import dev.warsha.remoteble.tools.core.hex
import dev.warsha.remoteble.tools.core.isAutoGeneratedClientIdentity
import dev.warsha.remoteble.tools.core.normalizeUuid
import dev.warsha.remoteble.tools.core.operationFailure
import dev.warsha.remoteble.tools.core.sigName
import dev.warsha.remoteble.tools.core.gattPropertyNames
import dev.warsha.remoteble.tools.core.readStandardInput
import dev.warsha.remoteble.tools.core.resolve
import dev.warsha.remoteble.tools.core.supports
import dev.warsha.remoteble.tools.core.unsupportedFeature
import dev.warsha.remoteble.tools.core.writeStandardOutput
import dev.warsha.remoteble.tools.core.writeStandardError
import kotlin.time.Clock
import kotlin.time.Duration
import kotlin.io.encoding.Base64
import kotlin.system.exitProcess
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonObjectBuilder
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonPrimitive

private const val MAX_TOKEN_BYTES = 8 * 1024

fun main(args: Array<String>) {
    val cli = buildCli()
    try {
        cli.parse(args)
    } catch (error: CliktError) {
        // `printHelpOnEmptyArgs` reports a missing command as a PrintHelpMessage that sets `error`,
        // but the type fixes `printError = false`, so Clikt would print the usage to stdout and
        // exit 0 -- telling a script the run succeeded when nothing ran. `error` is exactly the
        // distinction between help that was asked for and help that stands in for a refusal.
        if (error is PrintHelpMessage && error.error) {
            cli.getFormattedHelp(error)?.let { cli.echo(it, err = true) }
            cli.echo("Error: no command given", err = true)
            exitProcess(ExitCode.USAGE.value)
        }
        cli.echoFormattedHelp(error)
        exitProcess(if (error is UsageError) ExitCode.USAGE.value else error.statusCode)
    }
}

internal fun buildCli(): RootCommand {
    val root = RootCommand()
    val agent = AgentCommand().subcommands(
        CapabilitiesCommand(root),
        StatusCommand(root),
        SlotsCommand(root),
    )
    val descriptor = DescriptorCommand().subcommands(DescriptorReadCommand(root))
    val config = ConfigCommand().subcommands(ConfigShowCommand(root), ConfigValidateCommand(root))
    return root.subcommands(
        agent,
        ScanCommand(root),
        ConnectCommand(root),
        DisconnectCommand(root),
        InspectCommand(root),
        ReadCommand(root),
        descriptor,
        RssiCommand(root),
        ObserveCommand(root),
        WriteCommand(root),
        ReportCommand(root),
        SessionCommand(root),
        ShellCommand(root),
        config,
        SkillsCommand().subcommands(SkillInstallCommand(root), SkillDoctorCommand(root)),
    )
}

internal class GlobalOptions : OptionGroup("Global options") {
    val configPath: String? by option("--config", help = "YAML configuration path (or REMOTE_BLE_CONFIG).")
    val profile: String? by option("--profile", help = "Named configuration profile.")
    val endpoint: String? by option("--endpoint", help = "Override agent WebSocket endpoint.")
    val clientId: String? by option("--client-id", help = "Override stable client identifier.")
    val tokenStdin: Boolean by option("--token-stdin", help = "Read an agent bearer token from standard input (maximum 8 KiB).").flag()
    val json: Boolean by option("--json", help = "Emit one versioned JSON envelope.").flag()
    val jsonl: Boolean by option("--jsonl", help = "Emit one versioned JSON envelope per line.").flag()
    val quiet: Boolean by option("--quiet", help = "Emit only command-specific machine output.").flag()
    val output: String? by option("--output", help = "human, json, jsonl, hex, base64, raw, or quiet.")
        .choice("human", "json", "jsonl", "hex", "base64", "raw", "quiet")
    val logLevel: String? by option("--log-level", help = "audit or debug operational logging.").choice("audit", "debug")
}

private data class EffectiveOptions(
    val configPath: String?,
    val profile: String?,
    val endpoint: String?,
    val clientId: String?,
    val tokenStdin: Boolean,
    val json: Boolean,
    val jsonl: Boolean,
    val quiet: Boolean,
    val output: String?,
    val logLevel: String?,
)

/**
 * Refuses a command group invoked without one of its subcommands.
 *
 * Printing the usage text and stopping there is not enough: nothing says what went wrong, so the
 * reader gets a wall of help and has to infer it, and the text lands on stdout where a caller
 * piping the command receives help as data. The root also exited 2 while a group exited 0, which
 * told a script the run had succeeded when nothing had run at all.
 */
private fun CliktCommand.requireSubcommand() {
    if (currentContext.invokedSubcommand != null) return
    echo(getFormattedHelp(), err = true)
    echo("Error: no command given", err = true)
    throw ProgramResult(ExitCode.USAGE.value)
}

internal class RootCommand : CliktCommand(
    name = "remoteble",
) {
    private val global by GlobalOptions()
    private var active: EffectiveOptions? = null
    private var outputSequence: Long = 0
    private var copiedIdentityWarningEmitted = false

    init {
        versionOption("RemoteBLE CLI $CLI_VERSION")
        completionOption()
    }

    override fun run() {
        active = global.effectiveWith(null)
        requireSubcommand()
    }
    override fun help(context: Context): String = "A scriptable client for RemoteBLE agents."
    override val invokeWithoutSubcommand: Boolean = true

    private fun GlobalOptions.effectiveWith(local: GlobalOptions?): EffectiveOptions = EffectiveOptions(
        configPath = local?.configPath ?: configPath,
        profile = local?.profile ?: profile,
        endpoint = local?.endpoint ?: endpoint,
        clientId = local?.clientId ?: clientId,
        tokenStdin = tokenStdin || local?.tokenStdin == true,
        json = json || local?.json == true,
        jsonl = jsonl || local?.jsonl == true,
        quiet = quiet || local?.quiet == true,
        output = local?.output ?: output,
        logLevel = local?.logLevel ?: logLevel,
    )

    fun activate(local: GlobalOptions) {
        active = global.effectiveWith(local)
        val selected = checkNotNull(active)
        val selectedModes = listOf(selected.json, selected.jsonl, selected.quiet, selected.output != null).count { it }
        if (selectedModes > 1) throw CliFailure(ExitCode.USAGE, "Choose only one output mode")
    }

    private fun options(): EffectiveOptions = checkNotNull(active) { "CLI options have not been parsed" }

    fun config(): FileConfig = options().let {
        ConfigLoader.load(it.configPath, it.profile ?: environmentVariable("REMOTE_BLE_PROFILE")).first
    }

    fun resolvedConfig(): ResolvedConfig {
        val selected = options()
        val base = config().resolve(
            selected.endpoint ?: environmentVariable("REMOTE_BLE_ENDPOINT"),
            selected.clientId ?: environmentVariable("REMOTE_BLE_CLIENT_ID"),
        )
        if (!copiedIdentityWarningEmitted && base.agent.clientId?.let(::isAutoGeneratedClientIdentity) == true) {
            copiedIdentityWarningEmitted = true
            writeStandardError("remoteble: configured rble-auto client id appears copied; omit it to use this machine's persisted identity\n".encodeToByteArray())
        }
        return base.copy(
            scanDuration = environmentVariable("REMOTE_BLE_SCAN_DURATION")?.let(Duration::parse) ?: base.scanDuration,
            operationTimeout = environmentVariable("REMOTE_BLE_OPERATION_TIMEOUT")?.let(Duration::parse) ?: base.operationTimeout,
        )
    }

    fun auditLogger(): AuditLogger = AuditLogger(
        directory = environmentVariable("REMOTE_BLE_LOG_DIR") ?: config().defaults.logDirectory ?: AuditLogger.defaultLogDirectory(),
    )

    fun debugLoggingEnabled(): Boolean = (options().logLevel ?: environmentVariable("REMOTE_BLE_LOG_LEVEL") ?: config().defaults.logLevel).lowercase() == "debug"

    fun outputMode(): String = when {
        options().json -> "json"
        options().jsonl -> "jsonl"
        options().quiet -> "quiet"
        else -> options().output ?: environmentVariable("REMOTE_BLE_OUTPUT") ?: config().defaults.output
    }.lowercase()

    fun tokenFromStdinSelected(): Boolean = options().tokenStdin

    private fun operatorToken(config: FileConfig): String {
        val token = (config.agent.operatorTokenEnvironmentVariable?.let(::environmentVariable)
            ?: environmentVariable("REMOTE_BLE_OPERATOR_TOKEN"))
            ?: throw CliFailure(ExitCode.USAGE, "operator status requires REMOTE_BLE_OPERATOR_TOKEN or agent.operatorTokenEnvironmentVariable")
        val ordinary = environmentVariable(config.agent.tokenEnvironmentVariable)
        if (ordinary != null && ordinary == token) {
            throw CliFailure(ExitCode.USAGE, "operator and ordinary bearer credentials must be distinct")
        }
        return token
    }

    fun <T> gateway(operator: Boolean = false, action: suspend (RemoteBleGateway) -> T): T = runBlocking {
        val resolved = resolvedConfig()
        val ordinaryToken = if (options().tokenStdin) readTokenFromStdin() else null
        val operatorToken = if (operator) {
            operatorToken(config())
        } else {
            null
        }
        if (ordinaryToken != null && ordinaryToken == operatorToken) {
            throw CliFailure(ExitCode.USAGE, "operator and ordinary bearer credentials must be distinct")
        }
        val gateway = RemoteBleGateway.open(resolved, ordinaryToken, operatorToken)
        try {
            auditLogger().audit("remote.operation", endpoint = resolved.agent.endpoint, clientId = resolved.agent.clientId, result = "attempt")
            return@runBlocking action(gateway)
                .also { auditLogger().audit("remote.operation", endpoint = resolved.agent.endpoint, clientId = resolved.agent.clientId, result = "ok") }
        } catch (error: Throwable) {
            auditLogger().audit("remote.operation", endpoint = resolved.agent.endpoint, clientId = resolved.agent.clientId, result = "error", errorKind = error::class.simpleName)
            throw error
        } finally {
            gateway.close()
        }
    }

    fun openPersistentGateway(operator: Boolean = false): RemoteBleGateway = runBlocking {
        if (options().tokenStdin) {
            throw CliFailure(ExitCode.USAGE, "--token-stdin is unavailable for session and shell because stdin carries commands")
        }
        val resolved = resolvedConfig()
        val operatorToken = if (operator) {
            operatorToken(config())
        } else null
        RemoteBleGateway.open(resolved, operatorToken = operatorToken)
    }

    /**
     * Result data goes through the platform primitive rather than Clikt's `echo`, which reports no
     * write failure: a closed downstream pipe has to be observable here for the same reason it is in
     * the persistent session. Diagnostics stay on `echo(err = true)`, so stderr remains capturable
     * by the in-process command tests; stdout assertions belong in the packaged black-box tests.
     */
    private fun writeLine(text: String) = writeStandardOutput((text + "\n").encodeToByteArray())

    fun emit(type: String, value: JsonElement, human: String, quietValue: String? = null) {
        when (outputMode()) {
            "json" -> writeLine(codec.encodeToString(JsonElement.serializer(), envelope(type, value)))
            "jsonl" -> {
                outputSequence += 1
                writeLine(codec.encodeToString(JsonElement.serializer(), streamEnvelope(type, value)))
            }
            "quiet" -> quietValue?.let(::writeLine)
            "raw" -> quietValue?.encodeToByteArray()?.let(::writeStandardOutput)
            else -> writeLine(human)
        }
    }

    fun emitFailure(failure: CliFailure) {
        val structured = active?.let { runCatching { outputMode() }.getOrNull() in setOf("json", "jsonl") } == true
        if (structured) {
            val errorData = buildJsonObject {
                put("exitCode", failure.exitCode.value)
                put("message", failure.message)
                failure.agentError?.let { error ->
                    put("errorKind", error.kind.name)
                    error.gattStatus?.let { put("gattStatus", it) }
                    error.holder?.let { holder -> put("holder", buildJsonObject { put("principal", holder.principal); holder.clientId?.let { put("clientId", it) } }) }
                }
            }
            echo(
                codec.encodeToString(
                    JsonElement.serializer(),
                    if (outputMode() == "jsonl") { outputSequence += 1; streamEnvelope("error", errorData) } else envelope("error", errorData),
                ),
                err = true,
            )
        } else {
            echo("remoteble: ${failure.message}", err = true)
        }
    }

    fun emitBytes(type: String, bytes: ByteArray) {
        val mode = outputMode()
        if (mode == "raw") {
            writeStandardOutput(bytes)
            return
        }
        val encoded = if (mode == "base64") bytes.base64() else bytes.hex()
        emit(
            type,
            buildJsonObject {
                put("hex", bytes.hex())
                put("base64", bytes.base64())
                put("length", bytes.size)
            },
            encoded,
            encoded,
        )
    }

    fun require(caps: Set<String>, feature: AgentFeature, command: String) {
        if (!caps.supports(feature)) unsupportedFeature(feature, command)
    }

    private fun readTokenFromStdin(): String {
        val bytes = readStandardInput(MAX_TOKEN_BYTES + 1)
        if (bytes.size > MAX_TOKEN_BYTES) throw CliFailure(ExitCode.USAGE, "Token from stdin exceeds 8 KiB")
        val token = bytes.decodeToString().trim()
        if (token.isEmpty()) throw CliFailure(ExitCode.USAGE, "Token from stdin is empty")
        return token
    }

    private fun streamEnvelope(type: String, value: JsonElement) = buildJsonObject {
        put("schemaVersion", 1)
        put("type", type)
        put("timestamp", Clock.System.now().toString())
        put("sequence", outputSequence)
        put("data", value)
    }

    companion object {
        private const val MAX_TOKEN_BYTES = 8 * 1024
        private val codec = Json { prettyPrint = false; encodeDefaults = true }

        private fun envelope(type: String, value: JsonElement) = buildJsonObject {
            put("schemaVersion", 1)
            put("type", type)
            put("data", value)
        }

        fun failure(error: Throwable): CliFailure = operationFailure(error)
    }
}

internal abstract class RootChild(
    protected val root: RootCommand,
    name: String,
    private val commandHelp: String,
) : CliktCommand(name = name) {
    private val global by GlobalOptions()

    override fun help(context: Context): String = commandHelp

    protected fun execute(action: () -> Unit) {
        try {
            root.activate(global)
            action()
        } catch (result: ProgramResult) {
            throw result
        } catch (error: Throwable) {
            val failure = RootCommand.failure(error)
            root.emitFailure(failure)
            throw ProgramResult(failure.exitCode.value)
        }
    }
}

private class SkillsCommand : CliktCommand(name = "skills") {
    override fun run() = requireSubcommand()
    override fun help(context: Context): String = "Install and verify the bundled RemoteBLE Agent Skill locally."
    override val printHelpOnEmptyArgs: Boolean = true
    override val invokeWithoutSubcommand: Boolean = true
}

private abstract class SkillCommand(root: RootCommand, name: String, help: String) : RootChild(root, name, help) {
    private val target: List<String> by option("--target", help = "codex, gemini, claude, android-studio, or auto.").multiple()
    private val scope: String by option("--scope", help = "Install for one user or one project.").choice("user", "project").default("user")
    private val projectDirectory: String? by option("--project-dir", help = "Project root; defaults to nearest Git root or current directory.")

    protected fun installer(): SkillInstaller = SkillInstaller()
    protected fun scope(): SkillScope = if (scope == "user") SkillScope.USER else SkillScope.PROJECT
    protected fun destinations(installer: SkillInstaller): List<SkillDestination> = installer.resolve(scope(), target, projectDirectory)
    protected fun requestedTargets(): List<String> = target.ifEmpty { listOf("auto") }
    protected fun installData(results: List<SkillInstallResult>) = buildJsonObject {
        put("scope", scope)
        put("requestedTargets", JsonArray(requestedTargets().map(::JsonPrimitive)))
        put("skillVersion", skillVersion())
        put("cliVersion", CLI_VERSION)
        put("targets", buildJsonArray {
            results.forEach { result -> add(buildJsonObject {
                put("path", result.diagnosis.destination.path)
                put("targets", JsonArray(result.diagnosis.destination.targets.map { JsonPrimitive(it.cliName) }))
                put("status", result.diagnosis.status.name.lowercase())
                put("changed", result.changed)
                result.backup?.let { put("backup", it) }
            }) }
        })
    }
}

private class SkillInstallCommand(root: RootCommand) : SkillCommand(root, "install", "Install the embedded RemoteBLE skill without contacting an agent.") {
    private val force: Boolean by option("--force", help = "Back up and replace a modified or unmanaged copy.").flag()

    override fun run() = execute {
        val installer = installer()
        val results = destinations(installer).map { installer.install(it, force) }
        val human = buildString {
            append("scope=${scope().name.lowercase()} targets=${requestedTargets().joinToString(",")}")
            results.forEach { result ->
                append("\n${result.diagnosis.destination.path}: ${result.diagnosis.status.name.lowercase()}")
                result.backup?.let { append(" (backup: $it)") }
            }
        }
        root.emit("skills.install", installData(results), human)
    }
}

private class SkillDoctorCommand(root: RootCommand) : SkillCommand(root, "doctor", "Verify locally installed RemoteBLE skill copies.") {
    override fun run() = execute {
        val installer = installer()
        val diagnoses = destinations(installer).map(installer::diagnose)
        val data = buildJsonObject {
            put("scope", scope().name.lowercase())
            put("requestedTargets", JsonArray(requestedTargets().map(::JsonPrimitive)))
            put("skillVersion", skillVersion())
            put("cliVersion", CLI_VERSION)
            put("targets", buildJsonArray {
                diagnoses.forEach { diagnosis -> add(buildJsonObject {
                    put("path", diagnosis.destination.path)
                    put("targets", JsonArray(diagnosis.destination.targets.map { JsonPrimitive(it.cliName) }))
                    put("status", diagnosis.status.name.lowercase())
                    diagnosis.detail?.let { put("detail", it) }
                }) }
            })
        }
        val human = buildString {
            append("scope=${scope().name.lowercase()} targets=${requestedTargets().joinToString(",")}")
            diagnoses.forEach { diagnosis -> append("\n${diagnosis.destination.path}: ${diagnosis.status.name.lowercase()}") }
        }
        root.emit("skills.doctor", data, human)
        if (diagnoses.any { it.status != SkillStatus.CURRENT }) throw ProgramResult(ExitCode.FAILURE.value)
    }
}

private class AgentCommand : CliktCommand(name = "agent") {
    override fun run() = requireSubcommand()
    override fun help(context: Context): String = "Inspect agent capabilities and future-gated operations."
    override val printHelpOnEmptyArgs: Boolean = true
    override val invokeWithoutSubcommand: Boolean = true
}

private class CapabilitiesCommand(root: RootCommand) : RootChild(root, "capabilities", "Show the negotiated capability intersection.") {
    override fun run() = execute {
        val caps = root.gateway { it.capabilities().sorted() }
        val scanMode = caps.firstOrNull { it.startsWith("scan.concurrency.") }
            ?.removePrefix("scan.concurrency.") ?: "unknown"
        val data = buildJsonObject {
            put("capabilities", JsonArray(caps.map(::JsonPrimitive)))
            put("scanConcurrency", scanMode)
            put("handleTranslation", Capabilities.IDENTIFIER_TRANSLATION in caps)
        }
        root.emit(
            "agent.capabilities",
            data,
            (caps + "scan-concurrency=$scanMode").joinToString("\n"),
            caps.joinToString("\n"),
        )
    }
}

private class StatusCommand(root: RootCommand) : RootChild(root, "status", "Show official agent status when supported.") {
    private val operator: Boolean by option("--operator", help = "Use the configured operator token for full status details.").flag()
    override fun run() = execute {
        val status = root.gateway(operator) { gateway ->
            root.require(gateway.capabilities(), AgentFeature.STATUS, "agent status")
            RemoteOperationService(gateway, root.resolvedConfig().agent.endpoint, root.auditLogger()).status().also {
                if (operator && !it.operatorScope) {
                    throw CliFailure(ExitCode.AUTHENTICATION, "agent did not grant operator scope")
                }
            }
        }
        root.emit("agent.status", status.json(), status.human())
    }
}

private class SlotsCommand(root: RootCommand) : RootChild(root, "slots", "Show agent-global, lease-aware slot capacity when supported.") {
    override fun run() = execute {
        val slots = root.gateway { gateway ->
            root.require(gateway.capabilities(), AgentFeature.GLOBAL_SLOTS, "agent slots")
            RemoteOperationService(gateway, root.resolvedConfig().agent.endpoint, root.auditLogger()).slots()
        }
        root.emit(
            "agent.slots",
            buildJsonObject { put("free", slots.free); put("total", slots.total) },
            "free=${slots.free} total=${slots.total}",
        )
    }
}

private class ScanCommand(root: RootCommand) : RootChild(root, "scan", "Scan for BLE advertisements for a bounded duration.") {
    private val duration: String? by option("--duration", help = "Scan duration, e.g. 5s.")
    private val service: String? by option("--service", help = "Filter by advertised service UUID.")
    private val name: String? by option("--name", help = "Filter by advertised name.")
    private val minimumRssi: Int? by option("--minimum-rssi", help = "Local output filter; does not reduce radio work.").int()
    private val maximumEvents: Int by option("--max-events", help = "Maximum advertisements to collect.").int().default(100)

    override fun run() = execute {
        if (maximumEvents <= 0) throw CliFailure(ExitCode.USAGE, "--max-events must be positive")
        val filters = listOfNotNull(if (service != null || name != null) ScanFilter(service?.let(::normalizeUuid), name) else null)
        val deadline = duration?.let(Duration::parse) ?: root.resolvedConfig().scanDuration
        if (root.outputMode() == "jsonl") {
            root.gateway { gateway ->
                val scan = RemoteOperationService(gateway, root.resolvedConfig().agent.endpoint, root.auditLogger())
                    .managedScan(filters)
                var result = "complete"
                try {
                    result = collectBoundedStream(scan.events, maximumEvents, deadline) { ad ->
                        if (minimumRssi == null || ad.rssi >= minimumRssi!!) {
                            root.emit("scan.result", ad.json(), "${ad.device.value}\t${escapeDeviceText(ad.name).orEmpty()}\t${ad.rssi} dBm", ad.device.value)
                        }
                    }.reason.auditResult
                } catch (error: Throwable) {
                    result = "error"
                    throw error
                } finally {
                    kotlinx.coroutines.withContext(kotlinx.coroutines.NonCancellable) { runCatching { scan.stopAndAwait(result) } }
                }
            }
        } else {
            val ads = root.gateway { gateway ->
                RemoteOperationService(gateway, root.resolvedConfig().agent.endpoint, root.auditLogger())
                    .scan(filters, deadline, maximumEvents)
            }
                .filter { minimumRssi == null || it.rssi >= minimumRssi!! }
            val grouped = ads.withIndex().groupBy { it.value.device.value }
            val handles = grouped.keys.toList().sorted()
            val aggregate = handles.map { handle ->
                val indexed = grouped.getValue(handle)
                val first = indexed.first().value; val last = indexed.last().value
                buildJsonObject {
                    put("handle", handle); first.name?.let { put("name", escapeDeviceText(it)) }
                    put("rssi", last.rssi); put("eventCount", indexed.size); put("firstSeen", indexed.first().index); put("lastSeen", indexed.last().index)
                    put("serviceUuids", JsonArray(first.serviceUuids.map(::JsonPrimitive)))
                }
            }
            root.emit("scan", JsonArray(aggregate), handles.zip(aggregate).joinToString("\n") { (key, value) -> "$key\t${value["eventCount"]} events" }, handles.firstOrNull())
        }
    }
}

private class SelectorOptions : OptionGroup() {
    val name: String? by option("--name", help = "Select one exact advertised name when no handle is supplied.")
    val service: String? by option("--service", help = "Select one advertised service when no handle is supplied.")
}

private abstract class DeviceCommand(root: RootCommand, name: String, help: String) : RootChild(root, name, help) {
    private val handle: String? by argument("HANDLE", help = "RemoteBLE device handle from scan.").optional()
    private val selector by SelectorOptions()
    protected fun selection() = DeviceSelection(handle, selector.name, selector.service?.let(::normalizeUuid))
}

private class ConnectCommand(root: RootCommand) : DeviceCommand(root, "connect", "Connect a scanned device and retain its session lease until this command exits.") {
    override fun run() = execute {
        val handle = root.gateway { gateway ->
            RemoteOperationService(gateway, root.resolvedConfig().agent.endpoint, root.auditLogger())
                .connect(selection(), root.resolvedConfig().scanDuration)
        }
        root.emit("connect", buildJsonObject { put("handle", handle) }, "Connected $handle", handle)
    }
}

private class DisconnectCommand(root: RootCommand) : DeviceCommand(root, "disconnect", "Explicitly disconnect a device.") {
    override fun run() = execute {
        val handle = root.gateway { gateway ->
            RemoteOperationService(gateway, root.resolvedConfig().agent.endpoint, root.auditLogger())
                .disconnect(selection(), root.resolvedConfig().scanDuration)
        }
        root.emit("disconnect", buildJsonObject { put("handle", handle) }, "Disconnected $handle")
    }
}

private class InspectCommand(root: RootCommand) : DeviceCommand(root, "inspect", "Discover services, characteristics, and descriptors.") {
    override fun run() = execute {
        lateinit var handle: String
        val services = root.gateway { gateway ->
            val operations = RemoteOperationService(gateway, root.resolvedConfig().agent.endpoint, root.auditLogger())
            handle = operations.resolve(selection(), root.resolvedConfig().scanDuration)
            operations.inspect(handle)
        }
        val data = buildJsonArray {
            services.forEach { service ->
                add(buildJsonObject {
                    put("uuid", service.uuid)
                    put("characteristics", buildJsonArray {
                        service.characteristics.forEach { characteristic ->
                            add(buildJsonObject {
                                put("uuid", characteristic.uuid)
                                put("properties", JsonArray(gattPropertyNames(characteristic.properties).map(::JsonPrimitive)))
                                sigName(characteristic.uuid)?.let { put("name", it) }
                                put("descriptors", JsonArray(characteristic.descriptors.map(::JsonPrimitive)))
                            })
                        }
                    })
                })
            }
        }
        root.emit(
            "inspect",
            data,
            services.joinToString("\n") { service -> "${service.uuid}: ${service.characteristics.joinToString { it.uuid }}" },
            handle,
        )
    }
}

private data class CharacteristicSelection(val handle: String, val service: String, val characteristic: String)

private abstract class CharacteristicCommand(root: RootCommand, name: String, help: String) : RootChild(root, name, help) {
    private val handle: String by argument("HANDLE")
    private val service: String by argument("SERVICE_UUID")
    private val characteristic: String by argument("CHARACTERISTIC_UUID")
    protected fun characteristic() = CharacteristicSelection(handle, normalizeUuid(service), normalizeUuid(characteristic))
}

private class ReadCommand(root: RootCommand) : CharacteristicCommand(root, "read", "Read a characteristic value.") {
    override fun run() = execute {
        val selected = characteristic()
        root.emitBytes("read", root.gateway { gateway ->
            RemoteOperationService(gateway, root.resolvedConfig().agent.endpoint, root.auditLogger())
                .read(selected.handle, selected.service, selected.characteristic)
        })
    }
}

private class DescriptorCommand : CliktCommand(name = "descriptor") {
    override fun run() = requireSubcommand()
    override fun help(context: Context): String = "Read GATT descriptors."
    override val printHelpOnEmptyArgs: Boolean = true
    override val invokeWithoutSubcommand: Boolean = true
}

private class DescriptorReadCommand(root: RootCommand) : RootChild(root, "read", "Read a descriptor value.") {
    private val handle: String by argument("HANDLE")
    private val service: String by argument("SERVICE_UUID")
    private val characteristic: String by argument("CHARACTERISTIC_UUID")
    private val descriptor: String by argument("DESCRIPTOR_UUID")

    override fun run() = execute {
        val bytes = root.gateway { gateway ->
            root.require(gateway.capabilities(), AgentFeature.DESCRIPTORS, "descriptor read")
            RemoteOperationService(gateway, root.resolvedConfig().agent.endpoint, root.auditLogger())
                .readDescriptor(handle, normalizeUuid(service), normalizeUuid(characteristic), normalizeUuid(descriptor))
        }
        root.emitBytes("descriptor.read", bytes)
    }
}

private class RssiCommand(root: RootCommand) : DeviceCommand(root, "rssi", "Read the connected-link RSSI.") {
    override fun run() = execute {
        lateinit var handle: String
        val rssi = root.gateway { gateway ->
            root.require(gateway.capabilities(), AgentFeature.RSSI, "rssi")
            val operations = RemoteOperationService(gateway, root.resolvedConfig().agent.endpoint, root.auditLogger())
            handle = operations.resolve(selection(), root.resolvedConfig().scanDuration)
            operations.readRssi(handle)
        }
        root.emit("rssi", buildJsonObject { put("handle", handle); put("rssi", rssi) }, "$rssi dBm", rssi.toString())
    }
}

private class ObserveCommand(root: RootCommand) : CharacteristicCommand(root, "observe", "Stream bounded characteristic notifications.") {
    private val count: Int? by option("--count", help = "Maximum notifications to emit.").int()
    private val timeout: String? by option("--timeout", help = "Stream deadline.")
    private val unbounded: Boolean by option("--unbounded", help = "Use only when local policy explicitly permits an unbounded stream.").flag()

    override fun run() = execute {
        val limit = count
        val deadline = timeout
        if (limit != null && limit <= 0) throw CliFailure(ExitCode.USAGE, "--count must be positive")
        if (limit != null && limit > root.config().policy.maximumNotificationCount) {
            throw CliFailure(ExitCode.UNSUPPORTED, "--count exceeds local policy limit of ${root.config().policy.maximumNotificationCount}")
        }
        if (unbounded && (limit != null || deadline != null)) throw CliFailure(ExitCode.USAGE, "--unbounded cannot be combined with --count or --timeout")
        if (limit == null && deadline == null && (!unbounded || !root.config().policy.allowUnboundedStreams)) {
            throw CliFailure(ExitCode.USAGE, "observe requires --count or --timeout unless local policy allows unbounded streams")
        }
        if (root.outputMode() == "json") throw CliFailure(ExitCode.USAGE, "observe uses --jsonl for structured streaming output")
        val selected = characteristic()
        var sequence = 0L
        root.gateway { gateway ->
            val stream = RemoteOperationService(gateway, root.resolvedConfig().agent.endpoint, root.auditLogger())
                .managedObserve(selected.handle, selected.service, selected.characteristic)
            var result = "complete"
            suspend fun emitNotification(value: ByteArray) {
                sequence += 1
                if (root.outputMode() == "jsonl") {
                    root.emit(
                        "observe.notification",
                        buildJsonObject {
                            put("sequence", sequence)
                            put("timestamp", Clock.System.now().toString())
                            put("handle", selected.handle)
                            put("serviceUuid", selected.service)
                            put("characteristicUuid", selected.characteristic)
                            put("value", bytesJson(value))
                        },
                        value.hex(),
                        value.hex(),
                    )
                } else {
                    root.emitBytes("observe.notification", value)
                }
            }
            try {
                result = collectBoundedStream(
                    stream.events,
                    limit,
                    deadline?.let(Duration::parse),
                    ::emitNotification,
                ).reason.auditResult
            } catch (error: Throwable) {
                result = "error"
                throw error
            } finally {
                kotlinx.coroutines.withContext(kotlinx.coroutines.NonCancellable) { runCatching { stream.stopAndAwait(result) } }
            }
        }
    }
}

private class WriteCommand(root: RootCommand) : CharacteristicCommand(root, "write", "Write a characteristic only when agent-side enforcement is negotiated.") {
    private val hexPayload: String? by option("--hex", help = "Payload as hexadecimal bytes.")
    private val base64Payload: String? by option("--base64", help = "Payload as Base64 bytes.")
    private val textPayload: String? by option("--text", help = "Payload as UTF-8 text.")
    private val stdinEncoding: String? by option("--stdin", help = "Read stdin using this explicit encoding.").choice("hex", "base64", "text")
    private val writeType: String by option("--write-type", help = "BLE write acknowledgement behavior.").choice("with-response", "without-response").required()

    override fun run() = execute {
        if (root.tokenFromStdinSelected() && stdinEncoding != null) {
            throw CliFailure(ExitCode.USAGE, "--token-stdin cannot be combined with stdin write payload")
        }
        val parsedPayload = payload()
        val selected = characteristic()
        val withResponse = writeType == "with-response"
        val endpoint = root.resolvedConfig().agent.endpoint
        root.gateway { gateway ->
            WriteOperationService(gateway, root.config().policy, endpoint, root.auditLogger()).execute(
                WriteOperationService.Request(selected.handle, selected.service, selected.characteristic, parsedPayload, withResponse),
            )
        }
        root.emit("write", buildJsonObject { put("handle", selected.handle); put("length", parsedPayload.size); put("withResponse", withResponse) }, "Wrote ${parsedPayload.size} bytes to ${selected.handle}")
    }

    private fun payload(): ByteArray {
        val hex = hexPayload
        val base64 = base64Payload
        val text = textPayload
        val stdin = stdinEncoding
        val sourceCount = listOf(hex, base64, text, stdin).count { it != null }
        if (sourceCount != 1) throw CliFailure(ExitCode.USAGE, "Specify exactly one of --hex, --base64, --text, or --stdin")
        return when {
            hex != null -> decodeHex(hex)
            base64 != null -> decodeBase64(base64)
            text != null -> text.encodeToByteArray()
            else -> {
                val raw = readStandardInput(MAX_WRITE_STDIN_BYTES + 1)
                if (raw.size > MAX_WRITE_STDIN_BYTES) throw CliFailure(ExitCode.USAGE, "stdin write payload exceeds 64 KiB")
                when (stdin) {
                    "hex" -> decodeHex(raw.decodeToString())
                    "base64" -> decodeBase64(raw.decodeToString())
                    "text" -> raw
                    else -> error("write source was not selected")
                }
            }
        }
    }

    private companion object { const val MAX_WRITE_STDIN_BYTES = 64 * 1024 }
}

private class ReportCommand(root: RootCommand) : RootChild(root, "report", "Show recent local audit records as a diagnostic report.") {
    private val limit: Int by option("--limit", help = "Maximum audit records to include.").int().default(100)

    override fun run() = execute {
        if (limit <= 0) throw CliFailure(ExitCode.USAGE, "--limit must be positive")
        val records = root.auditLogger().records(limit)
        val data = buildJsonObject { put("records", JsonArray(records)) }
        val human = if (records.isEmpty()) {
            "No local audit records"
        } else {
            records.joinToString("\n") { record ->
                listOfNotNull(
                    record["timestamp"]?.jsonPrimitive?.content,
                    record["operation"]?.jsonPrimitive?.content,
                    record["result"]?.jsonPrimitive?.content,
                ).joinToString("\t")
            }
        }
        root.emit("report", data, human)
    }
}

private class ConfigCommand : CliktCommand(name = "config") {
    override fun run() = requireSubcommand()
    override fun help(context: Context): String = "Inspect and validate configuration."
    override val printHelpOnEmptyArgs: Boolean = true
    override val invokeWithoutSubcommand: Boolean = true
}

private class ConfigShowCommand(root: RootCommand) : RootChild(root, "show", "Show resolved configuration with secret sources redacted.") {
    override fun run() = execute {
        val resolved = root.resolvedConfig()
        val config = root.config()
        val data = buildJsonObject {
            put("schemaVersion", config.schemaVersion)
            put("agent", buildJsonObject {
                put("endpoint", resolved.agent.endpoint)
                put("clientId", resolved.agent.clientId ?: "derived")
                put("tokenEnvironmentVariable", resolved.agent.tokenEnvironmentVariable)
                put("operatorTokenEnvironmentVariable", resolved.agent.operatorTokenEnvironmentVariable ?: "unset")
            })
            put("policy", buildJsonObject {
                put("readOnly", resolved.policy.readOnly)
                put("maximumWriteBytes", resolved.policy.maximumWriteBytes)
            })
            put("logging", buildJsonObject {
                put("level", environmentVariable("REMOTE_BLE_LOG_LEVEL") ?: config.defaults.logLevel)
                put("directory", environmentVariable("REMOTE_BLE_LOG_DIR") ?: config.defaults.logDirectory ?: AuditLogger.defaultLogDirectory())
            })
        }
        root.emit(
            "config.show",
            data,
            "endpoint=${resolved.agent.endpoint}\nclientId=${resolved.agent.clientId ?: "derived"}\ntoken=${resolved.agent.tokenEnvironmentVariable} (environment)",
        )
    }
}

private class ConfigValidateCommand(root: RootCommand) : RootChild(root, "validate", "Validate strict YAML configuration.") {
    override fun run() = execute {
        ConfigLoader.validate(root.config())
        root.resolvedConfig() // include effective environment/profile identity in validation feedback.
        root.emit("config.validate", buildJsonObject { put("valid", true) }, "Configuration is valid")
    }
}

private fun AdvertisementDto.json(): JsonObject = buildJsonObject {
    put("handle", device.value)
    name?.let { put("name", escapeDeviceText(it)) }
    put("rssi", rssi)
    put("serviceUuids", JsonArray(serviceUuids.map(::JsonPrimitive)))
    put("manufacturerData", buildJsonObject {
        manufacturerData.forEach { (id, value) -> put(id.toString(), value.hex()) }
    })
}

private fun bytesJson(bytes: ByteArray): JsonObject = buildJsonObject {
    put("hex", bytes.hex())
    put("base64", bytes.base64())
    put("length", bytes.size)
}

private fun decodeHex(value: String): ByteArray {
    val normalized = value.trim()
    if (normalized.length % 2 != 0 || normalized.any { it.digitToIntOrNull(16) == null }) {
        throw CliFailure(ExitCode.USAGE, "--hex must contain an even number of hexadecimal digits")
    }
    return ByteArray(normalized.length / 2) { index ->
        ((normalized[index * 2].digitToInt(16) shl 4) or normalized[index * 2 + 1].digitToInt(16)).toByte()
    }
}

private fun decodeBase64(value: String): ByteArray = try {
    Base64.decode(value.trim())
} catch (_: IllegalArgumentException) {
    throw CliFailure(ExitCode.USAGE, "--base64 must contain valid Base64 data")
}

private fun AgentStatusDto.json(): JsonObject = buildJsonObject {
    agentInfo?.let { put("agentInfo", it) }; put("protocolVersion", protocolVersion); put("uptimeMs", uptimeMs); put("operatorScope", operatorScope)
    put("settings", buildJsonObject {
        put("leaseGraceMs", settings.leaseGraceMs); put("transportGraceMs", settings.transportGraceMs); put("exclusiveByDefault", settings.exclusiveByDefault); put("scanConcurrency", settings.scanConcurrency); put("strictIdentifiers", settings.strictIdentifiers); put("writePolicyEnforced", settings.writePolicyEnforced)
    })
    put("slots", buildJsonObject { put("free", slots.free); put("total", slots.total) })
    put("connectedClients", connectedClients); put("otherLeases", otherLeases)
    put("leases", buildJsonArray { leases.forEach { lease -> add(buildJsonObject {
        put("handle", lease.handle); lease.name?.let { put("name", it) }; lease.holder?.let { put("holder", it) }; put("mine", lease.mine)
        put("connected", lease.connected); put("inGrace", lease.inGrace); lease.remainingGraceMs?.let { put("remainingGraceMs", it) }
    }) } })
}

/**
 * Agent-supplied strings reach a terminal here. `agentInfo`, lease handles, and holder names are
 * chosen elsewhere - by the agent, or by whoever holds a lease - so they get the same escaping as an
 * advertised device name rather than being trusted because they came from the agent.
 */
internal fun AgentStatusDto.human(): String = buildString {
    appendLine(escapeDeviceText(agentInfo) ?: "RemoteBLE agent")
    appendLine("slots: free=${slots.free} total=${slots.total} leases=${leases.size + otherLeases}")
    leases.forEach { lease ->
        appendLine(
            "lease: ${escapeDeviceText(lease.handle)} holder=${escapeDeviceText(lease.holder) ?: "hidden"} " +
                "connected=${lease.connected} grace=${lease.remainingGraceMs ?: 0}ms",
        )
    }
}.trimEnd()

private fun JsonObjectBuilder.put(key: String, value: Any?) {
    put(key, when (value) {
        null -> JsonNull
        is String -> JsonPrimitive(value)
        is Int -> JsonPrimitive(value)
        is Long -> JsonPrimitive(value)
        is Boolean -> JsonPrimitive(value)
        is Double -> JsonPrimitive(value)
        else -> error("Unsupported JSON primitive for $key: ${value::class.simpleName}")
    })
}
